GET https://api.mapbox.com/directions/v5/mapbox/driving/-74.194811%2C40.805123%3B-74.024581%2C40.874524?alternatives=true&geometries=geojson&language=en&overview=full&steps=true&access_token=pk.eyJ1IjoiZG9va2RhIiwiYSI6ImNscTM3azN3OTA4dmEyaXF1bmg3cXRvbDUifQ.d1Ovd_n9PwJqc_MdGS66-A
